name: Spread.rpg
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: node bot.js
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}
          MONGODB_URL: ${{MONGODB_URI: ${{ secrets.MongoDbUrl }}
