name: Multibot
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: node bot.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODBURL }}
